### ISSUE TITLE
想請問需要另外將 ffmpeg 放進 demo 嗎？

### ISSUE THREAD

**Issue by b95505017** [pili-engineering/PLDroidCameraStreaming#11]
看到 demo 內只有 bridge so
對於 ffmpeg 這部分比較不熟，還請給予一些資訊
感謝！

**Comment by jpxiong** [comment]
你好，不需要再将 ffmpeg 放进 demo 里了。

**Comment by b95505017** [comment]
不過我跑了您的 demo 之後，看到 logcat 有吐  FFmpegMuxer﹕ FFmpegMuxer.prepare():I/O error
然後就沒什麼動靜了
不曉得可能是哪些原因呢？感謝！

**Comment by uch71109** [comment]
Hi, I have the same problem as above.

**Comment by jpxiong** [comment]
你可能需要开通 pili 的直播服务，然后创建一个 stream，然后如 README 里面描述的那样，需要获得一个 stream json string，并构造 JsonObject ，传入 sdk。不过这个 i/o error ，一般是因为网络连接异常的错误。

**Comment by jpxiong** [comment]
@uch71109 Hi, can you post your logs including the url ?

**Comment by b95505017** [comment]
@jpxiong 想再請問一下，所以目前不支援 pilli 以外的 RTMP server 是嗎？

**Comment by jpxiong** [comment]
是的。sdk 需要输入 stream 信息，而这个 stream 信息来自 pili。
