### ISSUE TITLE
Why is Pili pinging 103.24.223.18 (port 1230)

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#119]
I see in the Logs that Pili is trying to ping 103.23.223.18:1230? Why is that?

**Comment by jpxiong** [comment]
More logs ?

**Comment by gouravd** [comment]
W/System.err: java.net.SocketTimeoutException: failed to connect to /103.24.223.19 (port 1230) after 10000ms
W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
W/System.err:     at java.net.Socket.connect(Socket.java:882)
W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:148)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:64)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:51)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:226)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: java.net.ProtocolException: method does not support a request body: GET
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:212)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:64)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:51)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:226)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: java.net.ProtocolException: method does not support a request body: GET
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:212)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:64)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:51)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:226)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: org.json.JSONException: End of input at character 0 of 
W/System.err:     at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:156)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:312)
W/System.err:     at com.pili.pldroid.report.speed.c.f(SpeedCheck.java:332)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:249)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: java.net.SocketTimeoutException: failed to connect to /103.24.223.19 (port 1230) after 10000ms
W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
W/System.err:     at java.net.Socket.connect(Socket.java:882)
W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:148)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:64)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:51)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:226)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: java.net.ProtocolException: method does not support a request body: GET
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:212)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:64)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:51)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:226)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: java.net.ProtocolException: method does not support a request body: GET
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:212)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:64)
W/System.err:     at com.pili.pldroid.report.speed.a.a(HttpPostPing.java:51)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:226)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: org.json.JSONException: End of input at character 0 of 
W/System.err:     at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:156)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:312)
W/System.err:     at com.pili.pldroid.report.speed.c.f(SpeedCheck.java:332)
W/System.err:     at com.pili.pldroid.report.speed.c.e(SpeedCheck.java:249)
W/System.err:     at com.pili.pldroid.report.speed.c.a(SpeedCheck.java:28)
W/System.err:     at com.pili.pldroid.report.speed.c$1.run(SpeedCheck.java:106)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by gouravd** [comment]
Any updates

**Comment by jpxiong** [comment]
Fixing...

**Comment by gouravd** [comment]
Awesome thanks!!
