### ISSUE TITLE
Difference in Inbuilt Beauty filter and BeautyFilter glsl

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#154]
I am unable to reproduce the same effect using the BeautyFilter glsl.

For example the Inbuilt beauty filter setting with values 1.0, 1.0, 1.0 gives great result. What is the equivalent setting int he glsl file.

I tried playing with the params values but unable to get the bluriness that is visible in the inbuilt beauty filter
  vec4 params = vec4(0.33, 0.63, 0.4, 0.35);

Basically how do the params values correspond to the beautyLevel, redden, whiten. And what is the singleStepOffset value used in the Inbuilt beauty setting

**Comment by jpxiong** [comment]
Maybe you can use the built-in Face beauty feature, just enable it like this:

```
mCameraStreamingSetting.setBuiltInFaceBeautyEnabled(true);
```

**Comment by jpxiong** [comment]
The params values of built-in FaceBeauty are adjusted by some special algorithms.
