### ISSUE TITLE
Switch camera should not stop on going streaming.

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#17]
The current behaviour of Switch camera is that the stopStreaming() is called. That should not be the case for most of the use cases. The switching should be dynamic without stopping the streaming.

**Comment by gouravd** [comment]
Help..anyone? I would like to test use it but this is a deal-breaker at this point. Opensourcing would allow us to modify it to our needs, much faster

**Comment by jpxiong** [comment]
Sorry for the late reply. There is no plan to open the source code at present. The `stopStreaming` when switch camera issue is on going now.

**Comment by gouravd** [comment]
Thanks for the update. Approximately when can we expect the camera switch
to be fixed?

I am using Kickflip streaming sdk. It's open source and I was able to add
filters to video streaming. Your sdk looks great and I was testing it and
really liked it. But it does not have support of filters, square aspect
ratio. Otherwise we would have used it right away in our app. If it was
open source I could have added some of these features as well.

Hope you consider adding these features soon so that we can use it.

**Comment by jpxiong** [comment]
The `stopStreaming` issue is caused by ffmpeg. So we must remove it and implement the related part by ourselves. It's not easy to do it. There are so many detailed works to do, like packet the video/audio data, etc. Thus, I guess we will cost about at least a week to finish it. 

Filters will be supported in next stage, but not straightforwardly. We will support the related interface and you can use the API to do it easily.

Square aspect ratio, i will add it to my work schedule. BTW, what's the requirement used to ?

**Comment by gouravd** [comment]
We are a live streaming and video streaming App. But we work with square videos so that they can be easily displayed and played within the feed(like instagram feeds). Its a video related app, so filters is a big requirement atleast in near future. 

We initially started with Kickflip, but HLS did not suit us. So built an entirely new sdk inhouse for RTMP. We are an extremely small team and maintaining SDKs are not easy. So we were exploring additional options when we came across your SDK. Since it comes from Pili, we assume it would have faster cycles (release, bug fixes etc..) and would be lot more stable. For Android 4.1+ - 4.3 we will continue using FFMpeg directly. But for 4.3+ we intended to use SDKs like yours.

So the camera switch problem, square video output, live and dynamic filters are the biggest things that we require apart from the other great features your sdk already includes (like screenshot generator)

**Comment by gouravd** [comment]
One more requirement is to be able to record it locally instead of streaming. I am not sure if that is currently possible with your SDK.

**Comment by jpxiong** [comment]
Yes, locally record is supported. You just need simply remove the `setStreamingProfile(mProfile)`, as following:
```
        CameraStreamingSetting setting = new CameraStreamingSetting();
        setting.setCameraId(Camera.CameraInfo.CAMERA_FACING_BACK)
                .setContinuousFocusModeEnabled(true)
//                .setStreamingProfile(mProfile)
                .setCameraPrvSizeLevel(CameraStreamingSetting.PREVIEW_SIZE_LEVEL.MEDIUM)
                .setCameraPrvSizeRatio(CameraStreamingSetting.PREVIEW_SIZE_RATIO.RATIO_16_9);
```

But i'm not sure that's what you expected.

Please try it on version 1.3.0 (the Pull Request is ready, waiting for our server upgrade). The video recording locally can't play on v1.2.3.

**Comment by gouravd** [comment]
Thanks, where do I set the output location for local recording.

**Comment by jpxiong** [comment]
There is no API to set the output location for local recording. 

`Environment.getExternalStorageDirectory().getAbsolutePath() + "/pldroid-recording.mp4"` is the default output location.

The local recording is just for debugging at first.

**Comment by gouravd** [comment]
Is it possible to add api for local recording in next version? I believe it
should not be a very big change.

**Comment by jpxiong** [comment]
Sure.

**Comment by gouravd** [comment]
Awesome, thanks a lot.

**Comment by gouravd** [comment]
Thanks for adding support for Local recording api in 1.3.1. Also Stream update is a welcome change.

Is the Camera switch, without stopping Streaming, fixed in this version?

**Comment by jpxiong** [comment]
Not yet. Next version is the target.

**Comment by gouravd** [comment]
Hi how is the progress. Can we expect an update this week? Just that we are eager to test it out.

**Comment by jpxiong** [comment]
The ffmpeg had been removed successfully. Adding the logic of stopping connection and more test are what i am doing.

**Comment by gouravd** [comment]
So to confirm
1) In this new version, camera switch will not cause the streaming to stop
and start
2) In this new version, streaming quality change will not cause the
streaming to stop and start...

Am I correct?

On Wed, Sep 9, 2015 at 7:45 AM, jpxiong <notifications@github.com> wrote:

> The ffmpeg had been removed successfully. Adding the logic of stopping
> connection and more test are what i am doing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pili-engineering/PLDroidCameraStreaming/issues/17#issuecomment-138755557>
> .
>



-- 
Regards,
Das, DET Labs

**Comment by jpxiong** [comment]
Yes. That's right.

**Comment by gouravd** [comment]
Does this new version 1.3.2 fix the camera switching and quality switching issues with streaming stopping and restarting?

**Comment by jpxiong** [comment]
v1.3.2 just fix the issue caused by soft keyboard.

v1.3.3 is ready now, and i do the final test now.

**Comment by jpxiong** [comment]
https://github.com/pili-engineering/PLDroidCameraStreaming/pull/38

**Comment by gouravd** [comment]
Switching camera is still stopping the streaming. The code still shows the following. It still calls stopStreaming

public boolean switchCamera() {
        if(this.r) {
            Log.i("CameraStreamingManager", "Pure Audio Streaming, can\'t switch camera!");
            return false;
        } else {
            Log.i("CameraStreamingManager", "switchCamera current cameraid:" + this.m);
            this.c.b();
            this.stopStreaming();
            this.i();
            this.b.onPause();
            if(this.m == 0) {
                this.m = 1;
            } else {
                this.m = 0;
            }

            if(this.b(this.m)) {
                this.C = true;
            }

            this.b.onResume();
            return true;
        }
    }
