### ISSUE TITLE
Set Output size of Video to 360x640

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#21]
I can see the bitrate can be set via Video quality, but how do we set the video output size. I am interested in options like 360X640 and 480X854.Currently the SMALL preview generates 432x768 which is not a fit for our requirement. MEDIUM generates 480x854, but there is no preview size for 360x640

Could you introduce resolution 360x640? Its a definitive requirement for us.

Also my suggestion is that preview sizes names can be more explanatory like 360P, 480P etc. instead of SMALL, MEDIUM, LARGE

**Comment by jpxiong** [comment]
We use the way you mentioned at first, but we encountered many crash problems as many android phones doesn't support the specify preview size.

So we make a strategy: Use the SMALL, MEDIUM, LARGE from the `getSupportedPreviewSizes`. It can ensure choose the right preview size.

There are so many kinds of Android phones. We have to use the strategy above.

**Comment by gouravd** [comment]
I understand your point, but I did a google search and found that 360X640 is more common than the resolution used in SMALL (452 width)

The more appropriate would be to decouple PreviewSize from Output size.

Please reconsider replacing the current resolution in SMALL preview to something smaller, otherwise there is very little difference between the SMALL and MEDIUM

Ref: http://stackoverflow.com/questions/6272384/most-popular-screen-sizes-resolutions-on-android-phones

**Comment by jpxiong** [comment]
The values of SMALL, MEDIUM, LARGE  depend on the specific Android phone. We can't set an unsupported preview size to camera, because it's too dangerous as crash maybe occurred on some phones. 

We found, even the CTS required in some cases, many many Android phones didn't follow correctly. 

`The more appropriate would be to decouple PreviewSize from Output size.`
-> under consideration

**Comment by gouravd** [comment]
Got it!

Thanks for considering decoupling of Preview and Output sizes.

On Thu, Aug 27, 2015 at 9:41 PM, jpxiong <notifications@github.com> wrote:

> The values of SMALL, MEDIUM, LARGE depend on the specific Android phone.
> We can't set an unsupported preview size to camera, because it's too
> dangerous as crash maybe occurred on some phones.
>
> We found, even the CTS required in some cases, many many Android phones
> didn't follow correctly.
>
> The more appropriate would be to decouple PreviewSize from Output size.
> -> under consideration
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pili-engineering/PLDroidCameraStreaming/issues/21#issuecomment-135481258>
> .
>



-- 
Regards,
Das, DET Labs
