### ISSUE TITLE
Delay between the first packet and last packet in the muxing queue is 10008000 > 10000000: forcing output

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#24]
Intermittently I am getting this error and the activity hangs

Delay between the first packet and last packet in the muxing queue is 10008000 > 10000000: forcing output

**Comment by jpxiong** [comment]
That is the moment when the input drops due to some network issues, but it is back after a second or so. Can you provide more informations ?

**Comment by gouravd** [comment]
Does Pili have any debug tracing that I can turn on? Or let me know what kind of information are you looking for.

I am testing this on a 2mbps connection (Phone connected to Wifi)

My concern is that the whole activity stops responding after this happens. Any idea why the activity hangs?

**Comment by jpxiong** [comment]
If you provide the logs including the process, that will be prefer. (PS: You can remove the redundant information).

What's more, SDK  have provided the API `setNativeLoggingEnabled` to enable/disable the native logs.

BTW, how much probability it happens?

**Comment by gouravd** [comment]
I further debugged and found the hang was due to my code. I was trying to
connect to a service using Websocket which was hanging due to slow
connection.

You can close this issue.
