### ISSUE TITLE
Adaptive bitrate causing stream to stop and start

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#25]
I am using adaptive bitrate to stream. But the stream is stopping and restarting after each bitrate change.

Can this be achieved without stopping and restarting the stream?

Is this related to Ffmpeg dependency ( like camera switch)

**Comment by jpxiong** [comment]
Yes. Caused by FFmpeg. Next version will be OK.

**Comment by gouravd** [comment]
Awesome, will close this issue as duplicate of #17
