### ISSUE TITLE
armeabi .so files

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#29]
Currently Pili has only armeabi-v7a and arm64 support. Could you please also release armeabi files.

**Comment by gouravd** [comment]
Actually this is very critical, without armeabi, we are actually losing out lot of users

**Comment by jpxiong** [comment]
As i know , most of the newer android devices (above api 18) are using armv7a or arm64v8a. In fact, i didn't find the android 4.3 handset with ARMv5, v6 . It's not a good idea to provide the armeabi without hard float.

**Comment by gouravd** [comment]
I thought the same, but when I distributed a test version, few of our users
who use HTC Desire 510 2014 model complained about compatibility.

I would really request you to provide armeabi .so files or else I will lose
those important and active users.

Please consider my request.

**Comment by gouravd** [comment]
Also in our app we will be using opencv to add support for older versions
like 4.1+ .

We will have different code path for Android 4.1-4.2 and different code
path for 4.3+.

Opencv has files for armeabi. So if I create a folder for armeabi but do
not put pili files in there, those phones with armeabi processors for 4.3+
will crash or even won't compile.

I would again request you to provide armeabi support. It's very very
important for us.

**Comment by jpxiong** [comment]
We can provide it as your strong request. However, as we have no ARMv5, v6 android handsets at present, thus the armeabi .so file will be without any test.

**Comment by gouravd** [comment]
Thank you very much. Once we have the the files we will test with our beta tester and let you know. Can you provide for v1.3.1 (current versions) as well?

**Comment by jpxiong** [comment]
OK. Wait for minutes...

**Comment by jpxiong** [comment]
You can download from [here](http://7xliwg.com1.z0.glb.clouddn.com/libpldroid_ffmpegbridge.so).

**Comment by gouravd** [comment]
Thank you so much. Will try with few of my customers and let you know

**Comment by gouravd** [comment]
Can you please share the armeabi files for 1.3.2.

Can you include armeabi version in your releases directly?

**Comment by jpxiong** [comment]
> You can download from [here](http://7xliwg.com1.z0.glb.clouddn.com/libpldroid_ffmpegbridge.so).

Does this work fine ?

I will add the armeabi version in v1.3.3.

**Comment by gouravd** [comment]
Thanks a lot

Yes these work fine

**Comment by jpxiong** [comment]
https://github.com/pili-engineering/PLDroidCameraStreaming/pull/38
