### ISSUE TITLE
Exception while resuming (intermittently)

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#30]
Intermittently while resuming to the activity, I am getting the following exception

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.hardware.Camera.setPreviewTexture(android.graphics.SurfaceTexture)' on a null object reference

com.pili.pldroid.streaming.CameraStreamingManager.a (CameraStreamingManager.java:389)
com.pili.pldroid.streaming.CameraStreamingManager.a (CameraStreamingManager.java:31)
com.pili.pldroid.streaming.CameraStreamingManager$a.handleMessage (CameraStreamingManager.java:764)

**Comment by gouravd** [comment]
more stack


java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:255)
java.util.ArrayList.get (ArrayList.java:308)
com.pili.pldroid.streaming.av.a.a (CameraUtils.java:74)
com.pili.pldroid.streaming.CameraStreamingManager.a (CameraStreamingManager.java:405)
com.pili.pldroid.streaming.CameraStreamingManager.b (CameraStreamingManager.java:512)
com.pili.pldroid.streaming.CameraStreamingManager.onResume (CameraStreamingManager.java:169)

**Comment by jpxiong** [comment]
Can you provide the log including `CameraUtils` ?

**Comment by gouravd** [comment]
Issue not occurring anymore. Closing this, will reopen will issue reappears
