### ISSUE TITLE
Dynamic camera switching, Custom resolutions

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#36]
Since you are already using FFMpeg, we should allow using custom resolutions and not depend on Camera supported resolutions for final video output.

Previously we discussed that you would remove dependency on FFMpeg to allow dynamic camera switching, quality changing. But even with FFMpeg that should be possible

Kickflip SDK allows all that using FFMpeg. So technically it is possible.

https://github.com/Kickflip/kickflip-android-sdk

**Comment by jpxiong** [comment]
Really ? Does it support dynamic camera switching ? Please show me the code !

**Comment by gouravd** [comment]
https://github.com/Kickflip/kickflip-android-sdk/blob/af3aae5f1128d7376e67aefe11a3a1a3844be734/sdk/src/main/java/io/kickflip/sdk/fragment/BroadcastFragment.java

This above is the UI part that requests camera switch (mBroadcaster.requestOtherCamera();)

https://github.com/Kickflip/kickflip-android-sdk/blob/af3aae5f1128d7376e67aefe11a3a1a3844be734/sdk/src/main/java/io/kickflip/sdk/av/AVRecorder.java

This is parent class of mBroadcaster. This calls mCamEncoder.requestOtherCamera(); of the camera encoder class.

https://github.com/Kickflip/kickflip-android-sdk/blob/af3aae5f1128d7376e67aefe11a3a1a3844be734/sdk/src/main/java/io/kickflip/sdk/av/CameraEncoder.java

This is the camera encoder that does the actual switching. This calls requestCamera(int cameraNum)

public void requestCamera(int camera) {
        if (Camera.getNumberOfCameras() == 1) {
            Log.w(TAG, "Ignoring requestCamera: only one device camera available.");
            return;
        }
        mDesiredCamera = camera;
        if (mCamera != null && mDesiredCamera != mCurrentCamera) {
            // Hot swap camera
            mHandler.sendMessage(mHandler.obtainMessage(MSG_RELEASE_CAMERA));
            mHandler.sendMessage(mHandler.obtainMessage(MSG_REOPEN_CAMERA));
        }
    }


@Override
        public void handleMessage(Message inputMessage) {
            int what = inputMessage.what;
            Object obj = inputMessage.obj;

            CameraEncoder encoder = mWeakEncoder.get();
            if (encoder == null) {
                Log.w(TAG, "EncoderHandler.handleMessage: encoder is null");
                return;
            }

            try {
                switch (what) {
                    case MSG_SET_SURFACE_TEXTURE:
                        encoder.handleSetSurfaceTexture((Integer) obj);
                        break;
                    case MSG_FRAME_AVAILABLE:
                        encoder.handleFrameAvailable((SurfaceTexture) obj);
                        break;
                    case MSG_REOPEN_CAMERA:
                        encoder.openAndAttachCameraToSurfaceTexture();
                        break;
                    case MSG_RELEASE_CAMERA:
                        encoder.releaseCamera();
                        break;
                    case MSG_RELEASE:
                        encoder.handleRelease();
                        break;
                    case MSG_RESET:
                        encoder.handleReset((SessionConfig) obj);
                        break;
                    default:
                        throw new RuntimeException("Unexpected msg what=" + what);
                }
            } catch (IOException e) {
                Log.e(TAG, "Unable to reset! Could be trouble creating MediaCodec encoder");
                e.printStackTrace();
            }
        }


I have used this myself and I can say that the streaming does not stop and restart. Hope this helps

**Comment by jpxiong** [comment]
Yes, it helpful. I had been missed something. But MediaCodec doesn't support update bitrate dynamically API 18. Also i want to change the quality not only the bitrate. Thanks for your helpful information.

**Comment by gouravd** [comment]
Yes MediaCodec does not allow to update bitrate, I guess that is why they
rely on Ffmpeg to update the bitrate dynamically. I haven't looked deeper
but I believe that is how they do it.

I also believe Periscope dynamically updates bitrate only. Changing quality
is recommended for big change in internet connection speed. But for
temporary changes in internet speed, changing bitrate only is very helpful.

Also without the dependency on Ffmpeg we cannot predict the final
resolution and quality across different phones. But Ffmpeg allows to set a
constant output (eg 640x360 etc.)/across all platforms. We can then also
set custom aspect ratio(like square)

So I would really request and recommend to reintroduce dependency on Ffmpeg
and all

1) custom resolutions
2)Dynamic updating of bitrate
3)Custom aspect ratio (1:1)

**Comment by gouravd** [comment]
Also it would be very helpful if you can guide me how you integrate ActionScript in Android for using NetStream.

**Comment by jpxiong** [comment]
>Yes MediaCodec does not allow to update bitrate, I guess that is why they
rely on Ffmpeg to update the bitrate dynamically. I haven't looked deeper
but I believe that is how they do it.

NO! MediaCodec is for encoding and ffmpeg is for packeting and sending frames. If MediaCodec can't update bitrate dynamically, the whole process can't. 

> reintroduce dependency on Ffmpeg

We wouldn't reintroduce any more. 


> 1) custom resolutions
2)Dynamic updating of bitrate
3)Custom aspect ratio (1:1)

The reqs are on my work task list.

BTW, I's sorry to say that the `setLocalFileAbsolutePath` can't work on v1.3.3 or v1.3.4. I will add the api back on the later version.

**Comment by gouravd** [comment]
"BTW, I's sorry to say that the setLocalFileAbsolutePath can't work on v1.3.3 or v1.3.4. I will add the api back on the later version."

Any timeline when it might be re-introduced. It is actually very very important for us.

"The reqs are on my work task list."

So you mean without ffmpeg dependency, we can get Custom resolutions, Dynamic bitrate update and custom aspect ratio? That would be great.

**Comment by gouravd** [comment]
"I have no experience about that."
I asked about ActionScript because I thought you use ActionScript's NetStream for checking status of RTMP endpoint. Could you please let me know how you actually check the status and invoke events like Disconnected, NetBlocking etc..?

I am adding support for 4.1+ using JavaCV and need to add simillar capabilities of checking the rtmp atatus.

**Comment by gouravd** [comment]
"BTW, I's sorry to say that the setLocalFileAbsolutePath can't work on v1.3.3 or v1.3.4. I will add the api back on the later version."

Any timeline when it might be re-introduced. It is actually very very important for us.

**Comment by gouravd** [comment]
setLocalFileAbsolutePath is available in 1.3.7. Haven't tried it, but will it work?
