### ISSUE TITLE
V1.3.3 JNI error after PREPARING stage

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#39]
Pasting the logs (removed server name and app name)
Here is my setting

mProfile = new StreamingProfile();
            mSupportVideoQualities = mProfile.getSupportVideoQualities();
            mSupportAudioQualities = mProfile.getSupportAudioQualities();
            int videoquality = mSupportVideoQualities.containsKey("0") ? mSupportVideoQualities.get("0") : StreamingProfile.VIDEO_QUALITY_LOW3;
            int audioquality = mSupportAudioQualities.containsKey("0") ? mSupportAudioQualities.get("0") : StreamingProfile.AUDIO_QUALITY_MEDIUM1;
            mProfile.setVideoQuality(videoquality)
                    .setAudioQuality(audioquality)
                    .setStream(stream)
                            
                    .setSendingBufferProfile(new StreamingProfile.SendingBufferProfile(0.2f, 0.8f, 3.0f, 20 * 1000));

            CameraStreamingSetting setting = new CameraStreamingSetting();
            setting.setCameraId(Camera.CameraInfo.CAMERA_FACING_BACK)
                    .setContinuousFocusModeEnabled(false)
                    .setCameraPrvSizeLevel(CameraStreamingSetting.PREVIEW_SIZE_LEVEL.SMALL)
                    .setCameraPrvSizeRatio(CameraStreamingSetting.PREVIEW_SIZE_RATIO.RATIO_16_9);

            mCameraStreamingManager = new CameraStreamingManager(this, cameraholder, cameraPreview);
            mCameraStreamingManager.onPrepare(setting, mProfile);
            mCameraStreamingManager.setStreamingStateListener(this);

E/pldroid_core_rtmp? Parsing...
E/pldroid_core_rtmp? Parsed protocol: 0
E/pldroid_core_rtmp? Parsed host    : XXXXXXXXXXX
E/pldroid_core_rtmp? Parsed app     : XXXXXXXX
E/pldroid_core_rtmp? RTMP_Connect1, ... connected, handshaking
E/pldroid_core_rtmp? HandShake: Type Answer   : 03
E/pldroid_core_rtmp? HandShake: Server Uptime : 12647209
E/pldroid_core_rtmp? HandShake: FMS Version   : 0.0.0.0
E/pldroid_core_rtmp? RTMP_Connect1, handshaked
E/pldroid_core_rtmp? RTMP_SendPacket: fd=23, size=110
E/pldroid_core_rtmp? Invoking connect
E/pldroid_core_rtmp? RTMP_ReadPacket: fd=23
E/pldroid_core_rtmp? HandleServerBW: server BW = 5000000
E/pldroid_core_rtmp? RTMP_ReadPacket: fd=23
E/pldroid_core_rtmp? HandleClientBW: client BW = 5000000 2
E/pldroid_core_rtmp? RTMP_ReadPacket: fd=23
E/pldroid_core_rtmp? HandleChangeChunkSize, received: chunk size change to 4096
E/pldroid_core_rtmp? RTMP_ReadPacket: fd=23
E/pldroid_core_rtmp? RTMP_ClientPacket, received: invoke 190 bytes
E/pldroid_core_rtmp? (object begin)
E/pldroid_core_rtmp? Property: <Name:           no-name., STRING:	_result>
E/pldroid_core_rtmp? Property: <Name:           no-name., NUMBER:	1.00>
E/pldroid_core_rtmp? Property: <Name:           no-name., OBJECT>
E/pldroid_core_rtmp? (object begin)
E/pldroid_core_rtmp? Property: <Name:             fmsVer, STRING:	FMS/3,0,1,123>
E/pldroid_core_rtmp? Property: <Name:       capabilities, NUMBER:	31.00>
E/pldroid_core_rtmp? (object end)
E/pldroid_core_rtmp? Property: <Name:           no-name., OBJECT>
E/pldroid_core_rtmp? (object begin)
E/pldroid_core_rtmp? Property: <Name:              level, STRING:	status>
E/pldroid_core_rtmp? Property: <Name:               code, STRING:	NetConnection.Connect.Success>
E/pldroid_core_rtmp? Property: <Name:        description, STRING:	Connection succeeded.>
E/pldroid_core_rtmp? Property: <Name:     objectEncoding, NUMBER:	0.00>
E/pldroid_core_rtmp? (object end)
E/pldroid_core_rtmp? (object end)
E/pldroid_core_rtmp? HandleInvoke, server invoking <_result>
E/pldroid_core_rtmp? HandleInvoke, received result for method call <connect>
E/pldroid_core_rtmp? RTMP_SendPacket: fd=23, size=118
E/pldroid_core_rtmp? Invoking releaseStream
E/pldroid_core_rtmp? RTMP_SendPacket: fd=23, size=114
E/pldroid_core_rtmp? Invoking FCPublish
E/pldroid_core_rtmp? RTMP_SendPacket: fd=23, size=25
E/pldroid_core_rtmp? Invoking createStream
E/pldroid_core_rtmp? RTMP_ReadPacket: fd=23
E/pldroid_core_rtmp? RTMP_ClientPacket, received: invoke 29 bytes
E/pldroid_core_rtmp? (object begin)
E/pldroid_core_rtmp? Property: <Name:           no-name., STRING:	_result>
E/pldroid_core_rtmp? Property: <Name:           no-name., NUMBER:	4.00>
E/pldroid_core_rtmp? Property: NULL
E/pldroid_core_rtmp? Property: <Name:           no-name., NUMBER:	1.00>
E/pldroid_core_rtmp? (object end)
E/pldroid_core_rtmp? HandleInvoke, server invoking <_result>
E/pldroid_core_rtmp? HandleInvoke, received result for method call <createStream>
E/pldroid_core_rtmp? RTMP_SendPacket: fd=23, size=119
E/pldroid_core_rtmp? Invoking publish
E/pldroid_core_rtmp? RTMP_ReadPacket: fd=23
E/pldroid_core_rtmp? RTMP_ClientPacket, received: invoke 105 bytes
E/pldroid_core_rtmp? (object begin)
E/pldroid_core_rtmp? Property: <Name:           no-name., STRING:	onStatus>
E/pldroid_core_rtmp? Property: <Name:           no-name., NUMBER:	0.00>
E/pldroid_core_rtmp? Property: NULL
E/pldroid_core_rtmp? Property: <Name:           no-name., OBJECT>
E/pldroid_core_rtmp? (object begin)
E/pldroid_core_rtmp? Property: <Name:              level, STRING:	status>
E/pldroid_core_rtmp? Property: <Name:               code, STRING:	NetStream.Publish.Start>
E/pldroid_core_rtmp? Property: <Name:        description, STRING:	Start publishing>
E/pldroid_core_rtmp? (object end)
E/pldroid_core_rtmp? (object end)
E/pldroid_core_rtmp? HandleInvoke, server invoking <onStatus>
E/pldroid_core_rtmp? HandleInvoke, onStatus: NetStream.Publish.Start
A/art? art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: non-nullable argument was NULL
A/art? art/runtime/check_jni.cc:65]     in call to ReleaseStringUTFChars
A/art? art/runtime/check_jni.cc:65]     from void com.pili.pldroid.streaming.core.PLDroidStreamingCore.initialize(com.pili.pldroid.streaming.core.PLDroidStreamingCore$AVOptions, boolean)
A/art? art/runtime/check_jni.cc:65] "Thread-165546" prio=5 tid=50 Runnable
A/art? art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12fd0040 self=0xb75ad0b0
A/art? art/runtime/check_jni.cc:65]   | sysTid=25433 nice=0 cgrp=apps sched=0/0 handle=0xb7734988
A/art? art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=1 stm=1 core=1 HZ=100
A/art? art/runtime/check_jni.cc:65]   | stack=0xa171c000-0xa171e000 stackSize=1036KB
A/art? art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
A/art? art/runtime/check_jni.cc:65]   native: #00 pc 00004c58  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
A/art? art/runtime/check_jni.cc:65]   native: #01 pc 000034c1  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
A/art? art/runtime/check_jni.cc:65]   native: #02 pc 0025bebd  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+84)
A/art? art/runtime/check_jni.cc:65]   native: #03 pc 0023fb5b  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+162)
A/art? art/runtime/check_jni.cc:65]   native: #04 pc 000b102b  /system/lib/libart.so (art::JniAbort(char const*, char const*)+610)
A/art? art/runtime/check_jni.cc:65]   native: #05 pc 000b1751  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
A/art? art/runtime/check_jni.cc:65]   native: #06 pc 000b3b7b  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.128)+550)
A/art? art/runtime/check_jni.cc:65]   native: #07 pc 000bdba5  /system/lib/libart.so (art::CheckJNI::ReleaseStringUTFChars(_JNIEnv*, _jstring*, char const*)+68)
A/art? art/runtime/check_jni.cc:65]   native: #08 pc 00004b09  /data/app/in.voola.android.staging-1/lib/arm/libpldroid_streaming_core.so (Java_com_pili_pldroid_streaming_core_PLDroidStreamingCore_initialize+616)
A/art? art/runtime/check_jni.cc:65]   native: #09 pc 00675b63  /data/dalvik-cache/arm/data@app@in.voola.android.staging-1@base.apk@classes.dex (Java_com_pili_pldroid_streaming_core_PLDroidStreamingCore_initialize__Lcom_pili_pldroid_streaming_core_PLDroidStreamingCore_00024AVOptions_2Z+106)
A/art? art/runtime/check_jni.cc:65]   at com.pili.pldroid.streaming.core.PLDroidStreamingCore.initialize(Native method)
A/art? art/runtime/check_jni.cc:65]   at com.pili.pldroid.streaming.av.e.a(PLAVMuxer.java:136)
A/art? art/runtime/check_jni.cc:65]   at com.pili.pldroid.streaming.CameraStreamingManager.startStreaming(CameraStreamingManager.java:547)
A/art? art/runtime/check_jni.cc:65]   at in.voola.android.activity.BroadcastActivity$8$3.run(BroadcastActivity.java:760)
A/art? art/runtime/check_jni.cc:65]
A/art? art/runtime/runtime.cc:284] Runtime aborting...
A/art? art/runtime/runtime.cc:284] Aborting thread:
A/art? art/runtime/runtime.cc:284] "Thread-165546" prio=5 tid=50 Native
A/art? art/runtime/runtime.cc:284]   | group="" sCount=0 dsCount=0 obj=0x12fd0040 self=0xb75ad0b0
A/art? art/runtime/runtime.cc:284]   | sysTid=25433 nice=0 cgrp=apps sched=0/0 handle=0xb7734988
A/art? art/runtime/runtime.cc:284]   | state=R schedstat=( 0 0 0 ) utm=2 stm=14 core=1 HZ=100
A/art? art/runtime/runtime.cc:284]   | stack=0xa171c000-0xa171e000 stackSize=1036KB
A/art? art/runtime/runtime.cc:284]   | held mutexes= "abort lock" "mutator lock"(shared held)
A/art? art/runtime/runtime.cc:284]   native: #00 pc 00004c58  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
A/art? art/runtime/runtime.cc:284]   native: #01 pc 000034c1  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
A/art? art/runtime/runtime.cc:284]   native: #02 pc 0025bebd  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+84)
A/art? art/runtime/runtime.cc:284]   native: #03 pc 0023fb5b  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+162)
A/art? art/runtime/runtime.cc:284]   native: #04 pc 0022ee29  /system/lib/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*)+32)
A/art? art/runtime/runtime.cc:284]   native: #05 pc 0022f0cb  /system/lib/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+410)
A/art? art/runtime/runtime.cc:284]   native: #06 pc 0022f28b  /system/lib/libart.so (art::Runtime::Abort()+82)
A/art? art/runtime/runtime.cc:284]   native: #07 pc 000a7109  /system/lib/libart.so (art::LogMessage::~LogMessage()+1360)
A/art? art/runtime/runtime.cc:284]   native: #08 pc 000b1217  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1102)
A/art? art/runtime/runtime.cc:284]   native: #09 pc 000b1751  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
A/art? art/runtime/runtime.cc:284]   native: #10 pc 000b3b7b  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.128)+550)
A/art? art/runtime/runtime.cc:284]   native: #11 pc 000bdba5  /system/lib/libart.so (art::CheckJNI::ReleaseStringUTFChars(_JNIEnv*, _jstring*, char const*)+68)
A/art? art/runtime/runtime.cc:284]   native: #12 pc 00004b09  /data/app/in.voola.android.staging-1/lib/arm/libpldroid_streaming_core.so (Java_com_pili_pldroid_streaming_core_PLDroidStreamingCore_initialize+616)
A/art? art/runtime/runtime.cc:284]   native: #13 pc 00675b63  /data/dalvik-cache/arm/data@app@in.voola.android.staging-1@base.apk@classes.dex (Java_com_pili_pldroid_streaming_core_PLDroidStreamingCore_initialize__Lcom_pili_pldroid_streaming_core_PLDroidStreamingCore_00024AVOptions_2Z+106)
A/art? art/runtime/runtime.cc:284]   at com.pili.pldroid.streaming.core.PLDroidStreamingCore.initialize(Native method)
A/art? art/runtime/runtime.cc:284]   at com.pili.pldroid.streaming.av.e.a(PLAVMuxer.java:136)
A/art? art/runtime/runtime.cc:284]   at com.pili.pldroid.streaming.CameraStreamingManager.startStreaming(CameraStreamingManager.java:547)
A/art? art/runtime/runtime.cc:284]   at in.voola.android.activity.BroadcastActivity$8$3.run(BroadcastActivity.java:760)
A/art? art/runtime/runtime.cc:284] Dumping all threads without appropriate locks held: thread list lock mutator lock
A/art? art/runtime/runtime.cc:284] All threads:
A/art? art/runtime/runtime.cc:284] DALVIK THREADS (49):
A/art? art/runtime/runtime.cc:284] "main" prio=5 tid=1 Native
A/art? art/runtime/runtime.cc:284]   | group="" sCount=0 dsCount=0 obj=0x732ef480 self=0xb6fdd4c0
A/art? art/runtime/runtime.cc:284]   | sysTid=22132 nice=0 cgrp=apps sched=0/0 handle=0xb6f29ec8
A/art? art/runtime/runtime.cc:284]   | state=S schedstat=( 0 0 0 ) utm=437 stm=330 core=0 HZ=100
A/art? art/runtime/runtime.cc:284]   | stack=0xbe3ac000-0xbe3ae000 stackSize=8MB
A/art? art/runtime/runtime.cc:284]   | held mutexes=
A/art? art/runtime/runtime.cc:284]   kernel: sys_epoll_wait+0x2bc/0x398
A/art? art/runtime/runtime.cc:284]   kernel: sys_epoll_pwait+0x124/0x130
A/art? art/runtime/runtime.cc:284]   kernel: ret_fast_syscall+0x0/0x30
A/art? art/runtime/runtime.cc:284]   native: #00 pc 0003ca44  /system/lib/libc.so (__epoll_pwait+20)
A/art? art/runtime/runtime.cc:284]   native: #01 pc 000140d5  /system/lib/libc.so (epoll_pwait+26)
A/art? art/runtime/runtime.cc:284]   native: #02 pc 000140e3  /system/lib/libc.so (epoll_wait+6)
A/art? art/runtime/runtime.cc:284]   native: #03 pc 000123e7  /system/lib/libutils.so (android::Looper::pollInner(int)+98)
A/art? art/runtime/runtime.cc:284]   native: #04 pc 00012611  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
A/art? art/runtime/runtime.cc:284]   native: #05 pc 00080671  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
A/art? art/runtime/runtime.cc:284]   native: #06 pc 000b1cb7  /system/framework/arm/boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+102)
A/art? art/runtime/runtime.cc:284]   at android.os.MessageQueue.nativePollOnce(Native method)
A/art? art/runtime/runtime.cc:284]   at android.os.MessageQueue.next(MessageQueue.java:143)
A/art? art/runtime/runtime.cc:284]   at android.os.Looper.loop(Looper.java:122)
A/art? art/runtime/runtime.cc:284]   at android.app.ActivityThread.main(ActivityThread.java:5312)
A/art? art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke!(Native method)
A/art? art/runtime/runtime.cc:284]   at java.lang.reflect.Method.invoke(Method.java:372)
A/art? art/runtime/runtime.cc:284]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
A/art? art/runtime/runtime.cc:284]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
A/art? art/runtime/runtime.cc:284]
A/art? art/runtime/runtime.cc:284] "Heap thread pool worker thread 1" prio=5 tid=2 Native (still starting up)
A/art? art/runtime/runtime.cc:284]   | group="" sCount=0 dsCount=0 obj=0x0 self=0xb6fe3e60
A/art? art/runtime/runtime.cc:284]   | sysTid=22139 nice=0 cgrp=apps sched=0/0 handle=0xb7123328
A/art? art/runtime/runtime.cc:284]   | state=S schedstat=( 0 0 0 ) utm=0 stm=0 core=2 HZ=100
A/art? art/runtime/runtime.cc:284]   | stack=0xb4808000-0xb480a000 stackSize=1020KB
A/art? art/runtime/runtime.cc:284]   | held mutexes=
A/art? art/runtime/runtime.cc:284]   kernel: futex_wait_queue_me+0xe0/0x108
A/art? art/runtime/runtime.cc:284]   kernel: futex_wait+0x170/0x238
A/art? art/runtime/runtime.cc:284]   kernel: do_futex+0xfc/0x9fc
A/art? art/runtime/runtime.cc:284]   kernel: sys_futex+0x80/0x160
A/art? art/runtime/runtime.cc:284]   kernel: ret_fast_syscall+0x0/0x30
A/art? art/runtime/runtime.cc:284]   native: #00 pc 000126b8  /system/lib/libc.so (syscall+28)
A/art? art/runtime/runtime.cc:284]   native: #01 pc 000a9e43  /system/lib/libart.so (art::ConditionVariable::Wait(art::Thread*)+98)
A/art? art/runtime/runtime.cc:284]   native: #02 pc 00249d45  /system/lib/libart.so (art::ThreadPool::GetTask(art::Thread*)+64)
A/art? art/runtime/runtime.cc:284]   native: #03 pc 00249cdf  /system/lib/libart.so (art::ThreadPoolWorker::Run()+62)
A/art? art/runtime/runtime.cc:284]   native: #04 pc 0024a5cd  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+60)
A/art? art/runtime/runtime.cc:284]   native: #05 pc 00015e63  /system/lib/libc.so (__pthread_start(void*)+30)
A/art? art/runtime/runtime.cc:284]   native: #06 pc 00013e37  /system/lib/libc.so (__start_thread+6)
A/art? art/runtime/runtime.cc:284]   (no managed stack frames)
A/art? art/runtime/runtime.cc:284]

**Comment by jpxiong** [comment]
Could you please provide the android handset information ?

**Comment by gouravd** [comment]
It's Motorola MotoG 2nd Gen

**Comment by jpxiong** [comment]
The crash issue had been fixed. The v1.3.4 including the patch will be released tomorrow.

**Comment by gouravd** [comment]
Awesome. Eagerly waiting for it to try.

**Comment by jpxiong** [comment]
https://github.com/pili-engineering/PLDroidCameraStreaming/pull/41
