### ISSUE TITLE
[Question] SendingBufferProfile details

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#40]
Could you please explain how each setting of SendingBufferProfile controls the buffer

**Comment by jpxiong** [comment]
`SendingBuffer` is the buffer queue which storing the frame. It is for the adaptive bit-rate.

`SendingBufferProfile` is the profile for  `SendingBuffer`. There are some thresholds as following:

```
public static final float LOW_THRESHOLD_MIN = 0;
public static final float LOW_THRESHOLD_MAX = 1.0f;
public static final float LOW_THRESHOLD_DEFAULT = 0.2f;

public static final float HIGH_THRESHOLD_MIN = 0;
public static final float HIGH_THRESHOLD_MAX = 1.0f;
public static final float HIGH_THRESHOLD_DEFAULT = 0.8f;

public static final float DURATION_LIMIT_MIN = HIGH_THRESHOLD_MAX + 0.1f;
public static final float DURATION_LIMIT_MAX = 5.0f;
public static final float DURATION_LIMIT_DEFAULT = 3.0f;

public static final long LOW_THRESHOLD_TIMEOUT_MIN     = 10 * 1000; // ms
public static final long DEFAULT_LOW_THRESHOLD_TIMEOUT = 60 * 1000; // ms

// [LOW_THRESHOLD_MIN, LOW_THRESHOLD_MAX] && [LOW_THRESHOLD_MIN, high - 0.1)
private float mLowThreshold;

// [HIGH_THRESHOLD_MIN, HIGH_THRESHOLD_MAX] && (low + 0.1, HIGH_THRESHOLD_MAX]
private float mHighThreshold;

// [DURATION_LIMIT_MIN, DURATION_LIMIT_MAX]
private float mDurationLimit;

// [LOW_THRESHOLD_TIMEOUT_MIN, Long.MAX_VALUE)
// To measure the low buffering case
private long mLowThresholdTimeout;
```

SendingBuffer have some related state:
STATE.SENDING_BUFFER_EMPTY
STATE.SENDING_BUFFER_FULL // means the sending buffer is full and some frames will be removed tactically

STATE.SENDING_BUFFER_HAS_FEW_ITEMS  // means the network is  in **good** condition as few buffers to be sent out. `mLowThreshold` is the threshold for this.
STATE.SENDING_BUFFER_HAS_MANY_ITEMS // means the network is in **bad** condition as many buffers to be send out. `mHighThreshold` is the threshold for this.

`mLowThresholdTimeout`: if the network switch to good from bad , it needs `mLowThresholdTimeout` to wait . It's difficult to change to **good** except the network is really in good condition.

Hope this helps!

**Comment by gouravd** [comment]
Thanks for the info. This brings me to the 2nd question. Assume we have a stable internet connection at 1mbps. Assume all SendingBufferProfile settings at default and mLowThresholdTimeout at 10s. Now looking at the code below

case CameraStreamingManager.STATE.SENDING_BUFFER_HAS_FEW_ITEMS:
    mProfile.improveVideoQuality(1);
    mCameraStreamingManager.notifyProfileChanged(mProfile);
    return true;
case CameraStreamingManager.STATE.SENDING_BUFFER_HAS_MANY_ITEMS:
    mProfile.reduceVideoQuality(1);
    mCameraStreamingManager.notifyProfileChanged(mProfile);
    return true;

Suppose with start at Quality MEDIUM 1 (30fps, 500kbps). After 10 secs SENDING_BUFFER_HAS_FEW_ITEMS will be called and quality will be improved to MEDIUM_2. After 10 secs again SENDING_BUFFER_HAS_MANY_ITEMS will be called and so on..

And if the internet speed is very very good (eg 10mbps) then SENDING_BUFFER_HAS_FEW_ITEMS will be called over and over again.

What are your suggestions as to what should the upper limit and lower limit for changing quality be, assuming we start at Medium_1. 

For example, if we start at MEDIUM_1, should be go to a maximum of HIGH_1 and minimum of LOW_1. Or do you think it does not matter how high or low we go, depending on the internet speed.

**Comment by jpxiong** [comment]
`mDurationLimit` can be only between DURATION_LIMIT_MIN and DURATION_LIMIT_MAX. That's what exactly this means:
```
// [DURATION_LIMIT_MIN, DURATION_LIMIT_MAX]
private float mDurationLimit;
```

 `mLowThreshold` and `mHighThreshold` are the thresholds to trigger the `STATE.SENDING_BUFFER_HAS_FEW_ITEMS` and `STATE.SENDING_BUFFER_HAS_MANY_ITEMS`. Let me take an example, if you set `mLowThreshold` to 0.2 and `mHighThreshold` to 0.8, and 
1. `BufferQueue` remained <= 0.2 buffers, `STATE.SENDING_BUFFER_HAS_FEW_ITEMS` triggered
2. `BufferQueue` remained >= 0.8 buffers, `STATE.SENDING_BUFFER_HAS_MANY_ITEMS` triggered

Thus, `mDurationLimit` is useful to restrict the `STATE.SENDING_BUFFER_HAS_FEW_ITEMS` triggered. That means,

Only if `BufferQueue` remained <= 0.2 buffers with `mDurationLimit`, the `STATE.SENDING_BUFFER_HAS_FEW_ITEMS` triggered.

Your second question:

We have the algorithm to avoid the quality being changed all the time in stable network condition. To be honest, the algorithm need be improved. We trust we will do the best thing.

**Comment by gouravd** [comment]
Thanks, very helpful
