### ISSUE TITLE
V1.3.4 Camera switch still calls stopStreaming

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#42]
Switching camera is still stopping the streaming. The code still shows the following. It still calls stopStreaming. In the rtmp side, I see that the incoming bytes become zero and no data comes in.

public boolean switchCamera() {
....
this.stopStreaming();
this.i();
this.b.onPause();
....
}

**Comment by gouravd** [comment]
Quality change, though, is working as expected. But camera switch still calls stopStreaming()

**Comment by gouravd** [comment]
From the logs...I think the following is concerning...

"stopRecordingWithoutStoppingStreaming" is called but still its calling "stopStreaming"

I/TextureMovieEncoder? stopRecordingWithoutStoppingStreaming
I/CameraStreamingManager? stopStreaming
I/MicrophoneEncoder? stopRecording

Full logs pasted below:

I/CameraStreamingManager? switchCamera current cameraid:0
I/TextureMovieEncoder? stopRecordingWithoutStoppingStreaming
I/CameraStreamingManager? stopStreaming
I/MicrophoneEncoder? stopRecording
I/CameraStreamingManager? toggleRecording enabled:false
I/TextureMovieEncoder? releaseEncoder
I/PLAVMuxer? onEncoderReleased trackIndex=0
I/MediaCodec? (0xb77afff0) stop
I/MediaCodec? (0xb77afff0) release
I/Encoder? Released encoder
I/PLAVMuxer? onEncoderReleased trackIndex=1
I/MediaCodec? (0xb76d6468) stop
I/MediaCodec? (0xb76d6468) release
I/Encoder? Released encoder
I/CameraStreamingManager? releaseCamera -- done
I/CameraStreamingManager? level:SMALL,ratio:RATIO_16_9
I/CameraUtils? size.width:1280,size.height:960
I/CameraUtils? size.width:1280,size.height:720
I/CameraUtils? size.width:960,size.height:720
I/CameraUtils? size.width:864,size.height:480
I/CameraUtils? size.width:768,size.height:432
I/CameraUtils? size.width:720,size.height:480
I/CameraUtils? size.width:640,size.height:480
I/CameraUtils? size.width:320,size.height:240
I/CameraUtils? size.width:176,size.height:144
I/CameraUtils? after filter size.w:768, size.h:432
I/CameraUtils? after filter size.w:864, size.h:480
I/CameraUtils? after filter size.w:1280, size.h:720
I/CameraUtils? preview size width:768,height:432
I/CameraStreamingManager? setCameraPreviewSize width: 768,height:432
E/libEGL? called unimplemented OpenGL ES API
I/CameraStreamingManager? camera preview is ready
I/BroadcastActivity? onStateChanged state:7
I/BroadcastActivity? onStateChanged state:8
I/BroadcastActivity? isSupportedTorch=false
I/BroadcastActivity? onStateChanged state:1

**Comment by jpxiong** [comment]
I had noticed that. Thanks.

**Comment by gouravd** [comment]
Quick question, will this be fixed soon or is it complex?

**Comment by jpxiong** [comment]
Had fixed. 

V1.3.5 will be released after the other patches finished.

**Comment by gouravd** [comment]
Fixed in 1.3.5. closing
