### ISSUE TITLE
[Feature Requests] Please consider the following feature requests

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#46]
Firstly would like to thank for such a great library. I have been very happy to move to Pili from our own custom library. This library has shaped up great in the past 1 month or so. The separation of Preview from actual output in v1.3.5 is the best update so far. I am loving it. 

But there are few features that is missing, we would like to have, which we had in our library but are missing from Pili. Could you consider adding them in upcoming versions and could you let us know if these are feasible and approximate timeline

1) Pinch Zoom Camera during streaming (High priority)
2) Filters API. Plug-n-Play modular architecture probably, so that we can add our own filters later. (High priority)
3) Square aspect ratio (Low priority)

**Comment by jpxiong** [comment]
I would really strong recommend you to upgrade to v1.3.6.

1) Pinch Zoom Camera during streaming.
-> I think v1.3.7 maybe ok

2) Filters API. 
-> We have the plan. But there isn't timeline yet.

3) Square aspect ratio
-> Sorry, i need to deal with the task from my work list first.

**Comment by gouravd** [comment]
I am already testing 1.3.6. Will provide feedback once I am comfortable
with the results.

Aspect Ratio is of low priority, so you can ignore that as of now. Filters
is more important for us than Square aspect ratio.

Also if you can publish any tentative roadmap, it would be great.

On Tue, Sep 22, 2015 at 7:34 PM, jpxiong <notifications@github.com> wrote:

> I would really strong recommend you to upgrade to v1.3.6.
>
> 1) Pinch Zoom Camera during streaming.
> -> I think v1.3.7 maybe ok
>
> 2) Filters API.
> -> We have the plan. But there isn't timeline yet.
>
> 3) Square aspect ratio
> -> Sorry, i need to deal with the task from my work list first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pili-engineering/PLDroidCameraStreaming/issues/46#issuecomment-142298389>
> .
>



-- 
Regards,
Das, DET Labs

**Comment by gouravd** [comment]
4) Recording to phone simultaneously while streaming.

**Comment by gouravd** [comment]
5) Click to Focus (along with continuous focus which is already present)
