### ISSUE TITLE
[Issue] pili 1.3.7 Crash on CameraStreamingManager.onPause

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#50]
App crashing on v1.3.7 on CameraStreamingManage.onPause. But if we start streaming atleast once, then this does not crash on subsequent calls. For example. If the activity is opened and we press back button to close, it crashes. But if we start streaming once, then this call does not crash on subsequent activity open and close.

@Override
    public void onPause() {
        super.onPause();
        getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

        if (mCameraStreamingManager != null) {
            mCameraStreamingManager.onPause();
        }
    }

Logs

I/CameraStreamingManager: releaseCamera -- done
I/CameraSurfaceRenderer: notifyPausing +
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: in.voola.android.staging, PID: 13258
E/AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {in.voola.android.staging/in.voola.android.activity.BroadcastActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.pili.pldroid.streaming.av.video.c.c()' on a null object reference
E/AndroidRuntime:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3312)
E/AndroidRuntime:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3259)
E/AndroidRuntime:     at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3234)
E/AndroidRuntime:     at android.app.ActivityThread.access$1000(ActivityThread.java:148)
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
E/AndroidRuntime:  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.pili.pldroid.streaming.av.video.c.c()' on a null object reference
E/AndroidRuntime:     at com.pili.pldroid.streaming.av.video.b.a(TextureMovieEncoder.java:124)
E/AndroidRuntime:     at com.pili.pldroid.streaming.av.video.a.a(CameraSurfaceRenderer.java:107)
E/AndroidRuntime:     at com.pili.pldroid.streaming.CameraStreamingManager.onPause(CameraStreamingManager.java:196)
E/AndroidRuntime:     at in.voola.android.activity.BroadcastActivity.onPause(BroadcastActivity.java:961)
E/AndroidRuntime:     at android.app.Activity.performPause(Activity.java:6064)
E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1317)
E/AndroidRuntime:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3292)
E/AndroidRuntime:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3259) 
E/AndroidRuntime:     at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3234) 
E/AndroidRuntime:     at android.app.ActivityThread.access$1000(ActivityThread.java:148) 
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310) 
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by gouravd** [comment]
The current workaround is to wrap the call to CameraStreamingManager.onPause() in a try-catch block

try {
                mCameraStreamingManager.onPause();
            }catch (Exception ex){

            }

**Comment by jpxiong** [comment]
Please test it on v1.3.8. Thanks

**Comment by gouravd** [comment]
Fixed in 1.3.8. Thanks a lot
