### ISSUE TITLE
[Question] How to record locally

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#51]
I understand we have API setLocalFileAbsolutePath. But I am not sure how to use it to locally save video to file.

1) mProfile.setVideoQuality(videoquality)
                    .setAudioQuality(audioquality)
                    .setEncodingSizeLevel(StreamingProfile.VIDEO_ENCODING_SIZE_QVGA)
                    .setStream(stream)
                    .setLocalFileAbsolutePath(Util.getVideoOutputPath() + "/recording.mp4")
                    .setSendingBufferProfile(new StreamingProfile.SendingBufferProfile(0.2f, 0.8f, 3.0f, 10 * 1000));

If I use the above then streaming happens but recording to local file does not happen. if I comment ut setStream(stream), then we get IOError saying rtmp is null.

Please guide.

**Comment by gouravd** [comment]
In the logs I see 

09-25 16:56:24.272 30956-32748/in.voola.android.staging I/CameraStreamingManager: startStreaming mRecordingEnabled=false,mIsPreviewReady=true,mIsOnlyAudioStreaming=false

so I assume there has to be a way to set mRecordingEnabled=true

**Comment by gouravd** [comment]
Looking for help...Anyone used this?

**Comment by jpxiong** [comment]
Sorry for the late replay as the Dragon Boat Festival. We are focusing on the stability of the sdk，thus the feature you requested haven't implemented. 

In fact, it is very easy to do that if use pili streaming cloud service. pili will store the streaming data into Qiniu cload storage, and provide the api to covert the streaming data to mp4 or other types.

At present, the locally recording had been failed after removing the ffmpeg dependency. I'm considering add it back now.

**Comment by gouravd** [comment]
"Sorry for the late replay as the Dragon Boat Festival". Did not know about it. Hope you enjoyed the festival

"In fact, it is very easy to do that if use pili streaming cloud service". This is one option, but the easiest is to save it locally, so that users do not have to download it and they can record the moment even if there is no internet

"I'm considering add it back now." - Great news, thanks a lot.

**Comment by jpxiong** [comment]
Sorry. I'm afraid i have no time to implement the recording locally. 

But i have an idea that the sdk can provide the callback which take the h.264/aac encoding datas as the parameter, and you can use [mp4parser](https://github.com/sannies/mp4parser) to do it in the callback.

What do you think of the idea?

**Comment by gouravd** [comment]
That sounds fine to me. But I guess you might have to elaborate it a bit
about the exact callback that PILI would expose and how exactly I can use
that data. A small example would greatly help.

**Comment by gouravd** [comment]
Will you be also exposing API that we can use similarly for adding our own filters in upcoming version?

**Comment by gouravd** [comment]
Any estimate when can we expect this feature?

**Comment by gouravd** [comment]
A quick ping to check if there is any estimated time for the next update release

**Comment by gouravd** [comment]
Is this possible in the new 1.4.1?

**Comment by gouravd** [comment]
What is the recommended way to record byte[] frames in OnPreviewFrame to mp4 file?

**Comment by gouravd** [comment]
Still waiting for your response on how to record locally in v1.4.1

**Comment by gouravd** [comment]
Is recording possible in 1.4.1?

**Comment by gouravd** [comment]
Is recording possible in 1.4.3?

**Comment by jpxiong** [comment]
We thought the locally recording is not good idea for live streaming. There is no plan to support that.

**Comment by gouravd** [comment]
The IOS eqivalent of this library (PLCameraStreamingKIt) allows to record locally. So do you still think it is not required in Android version?
