### ISSUE TITLE
Can you introduce VIDEO_ENCODING_SIZE 360X640

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#61]
Can you introduce VIDEO_ENCODING_SIZE 360X640?

**Comment by gouravd** [comment]
Re-requesting feature for next version

**Comment by gouravd** [comment]
Re-requesting feature for next version

**Comment by gouravd** [comment]
Re-requesting feature for next version

**Comment by jpxiong** [comment]
You can do it now.

`StreamingProfile.setPreferredVideoEncodingSize(int width , int height)` is available for v1.4.5.

**Comment by gouravd** [comment]
Great, thanks
