### ISSUE TITLE
Camera Zoom and Click-To-Focus feature

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#62]
Can you please add Pinch Zoom and Click-To-Focus feature as well. I used the below code to add that to camera

@Override
    public boolean onTouchEvent(MotionEvent event) {
        if(camera == null)
            return false;
        // Get the pointer ID
        Camera.Parameters params = camera.getParameters();
        int action = event.getAction();

        if (event.getPointerCount() > 1) {
            // handle multi-touch events
            if (action == MotionEvent.ACTION_POINTER_DOWN) {
                mDist = getFingerSpacing(event);
            } else if (action == MotionEvent.ACTION_MOVE && params.isZoomSupported()) {
                camera.cancelAutoFocus();
                handleZoom(event, params);
            }
        } else {
            // handle single touch events
            if (action == MotionEvent.ACTION_UP) {
                handleFocus(event, params);
            }
        }
        return true;
    }

    private void handleZoom(MotionEvent event, Camera.Parameters params) {
        int maxZoom = params.getMaxZoom();
        int zoom = params.getZoom();
        float newDist = getFingerSpacing(event);
        if (newDist > mDist) {
            //zoom in
            if (zoom < maxZoom)
                zoom++;
        } else if (newDist < mDist) {
            //zoom out
            if (zoom > 0)
                zoom--;
        }
        mDist = newDist;
        params.setZoom(zoom);
        camera.setParameters(params);
    }

    public void handleFocus(MotionEvent event, Camera.Parameters params) {
        if (params.getMaxNumFocusAreas() == 0)
        {
            return;
        }

        int pointerId = event.getPointerId(0);
        int pointerIndex = event.findPointerIndex(pointerId);
        // Get the pointer's current position
        float x = event.getX(pointerIndex);
        float y = event.getY(pointerIndex);

        List<String> supportedFocusModes = params.getSupportedFocusModes();
        if (supportedFocusModes != null && supportedFocusModes.contains(Camera.Parameters.FOCUS_MODE_AUTO)) {

            float touchMajor = event.getTouchMajor();
            float touchMinor = event.getTouchMinor();
            Rect touchRect = new Rect((int)(x - touchMajor / 2), (int)(y - touchMinor / 2), (int)(x + touchMajor / 2), (int)(y + touchMinor / 2));

            Rect focusArea = new Rect();

            focusArea.set(touchRect.left * 2000 / cameraPreviewFrame.getWidth() - 1000,
                    touchRect.top * 2000 / cameraPreviewFrame.getHeight() - 1000,
                    touchRect.right * 2000 / cameraPreviewFrame.getWidth() - 1000,
                    touchRect.bottom * 2000 / cameraPreviewFrame.getHeight() - 1000);

            // Submit focus area to camera

            ArrayList<Camera.Area> focusAreas = new ArrayList<Camera.Area>();
            focusAreas.add(new Camera.Area(focusArea, 1000));

            params.setFocusMode(Camera.Parameters.FOCUS_MODE_AUTO);
            params.setFocusAreas(focusAreas);
            camera.setParameters(params);

            // Start the autofocus operation
            camera.autoFocus(new Camera.AutoFocusCallback() {
                @Override
                public void onAutoFocus(boolean b, Camera camera) {
                    // currently set to auto-focus on single touch
                }
            });
        }
    }

    /** Determine the space between the first two fingers */
    private float getFingerSpacing(MotionEvent event) {
        // ...
        float x = event.getX(0) - event.getX(1);
        float y = event.getY(0) - event.getY(1);
        return (float)Math.sqrt(x * x + y * y);
    }

**Comment by gouravd** [comment]
Re-requesting this feature for next version

**Comment by gouravd** [comment]
Re-requesting this feature for next version

**Comment by gouravd** [comment]
Re-requesting this feature for next version

**Comment by jpxiong** [comment]
v1.5.0 is OK for this issue.
