### ISSUE TITLE
libc Fatal issue when camerastreamingmanager.CaptureFrame is called in quick succession

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#63]
I/CameraSurfaceRenderer: captureFrame width:272, height:480
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x801 in tid 32358 (GLThread 5020)

This happens when I call CaptureFrame frequently, like frequent clicking on the button that calls CaptureFrame

I had never seen this issue with earlier versions

**Comment by gouravd** [comment]
on Android 4.4 device, the 2nd consecutive call to CaptureFrame crashes with
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x801 in tid 32358 (GLThread 5020)

**Comment by jpxiong** [comment]
Could you please provide more informations ?Thanks.

**Comment by gouravd** [comment]
Call 1: handler.postDelayed(screenshotThread, 500);
Call 1 always succeeds. 

Call 2: handler.postDelayed(screenshotThread, 500);
Call 2 intermittently fails on my Motorola G2 (Android 5.0.1) and always on Micromax Yureka (4.4.4)

If I call handler.postDelayed(screenshotThread) more frequently (like once in every 5 secs) it crashes on my Motorola as well.

This is reproducible even when the onFrameCaptured function is empty,

private Runnable screenshotThread = new Runnable() {
        @Override
        public void run() {
                    @Override
                    public void onFrameCaptured(Bitmap bmp) {
                        
                    }
            };
    };

**Comment by jpxiong** [comment]
Any logs ?

**Comment by gouravd** [comment]
I/CameraSurfaceRenderer: captureFrame width:272, height:480
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x801 in tid 32358 (GLThread 5020)

This is the only thing I saw. I will alter my code to reproduce the issue and share the complete logs too

**Comment by jpxiong** [comment]
More Debug logs will be helpful to handle the issue. Thanks.

**Comment by jpxiong** [comment]
I think the following way to catch logs will be more effective：
```
adb shell logcat -v time thread | tee ~/log.log
```

**Comment by gouravd** [comment]
So I clicked on a button which called mCameraStreamingManager.captureFrame. Then I started adb logging and then clicked the button again to call mCameraStreamingManager.captureFrame again and it crashed.

Time when the error occurs - 11-17 17:44:19.701 

[log.txt](https://github.com/pili-engineering/PLDroidCameraStreaming/files/36640/log.txt)

**Comment by jpxiong** [comment]
The `log.txt` is very valuable for debugging. Thanks.

**Comment by jpxiong** [comment]
Had been fixed. The next version will contain the PATCH.

**Comment by gouravd** [comment]
Awesome news. Thanks

**Comment by gouravd** [comment]
This is solved in 1.4.3
