### ISSUE TITLE
onPreviewFrame is not called

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#66]
I followed the instruction and the Demo code to implement StreamingPreviewCallback (not SurfaceTextureCallback).

But I do not see the onPreviewFrame being called. What am I doing wrong?

Also what is the proper way to save the byte[] data to mp4 file?

**Comment by jpxiong** [comment]
You should implement `StreamingPreviewCallback` and invoke `mCameraStreamingManager.setStreamingPreviewCallback(your implemented class);`

`byte[]` is not encoded data, just YUV data.

**Comment by gouravd** [comment]
I implemented SurfacePreviewCallback in main activity

public class BroadcastActivity extends  ImmersiveActivity implements CameraStreamingManager.StreamingStateListener, StreamingPreviewCallback

@Override
    public void onPreviewFrame(byte[] bytes, Camera _camera)
    {
        camera = _camera;
    }

and later in code I do this 

mCameraStreamingManager.setStreamingPreviewCallback(this);

but the onPreviewFrame is not called.

**Comment by gouravd** [comment]
Just found that the onPreviewFrame is called only when I am using SW_VIDEO_WITH_SW_AUDIO_CODEC. Its not working with W_VIDEO_WITH_HW_AUDIO_CODEC

Is it by design?

**Comment by jpxiong** [comment]
Yep.

**Comment by gouravd** [comment]
Will it change in near future?

Even we cannot add filters if the onDrawFrame() callback is not called for HW_VIDEO_WITH_HW_AUDIO_CODEC
