### ISSUE TITLE
How to add Video Filters 

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#67]
in 1.4.1 in onDrawFrame() we could process the textureId to add filters. But onDrawFrame is only called when we use Software encoding and not the Hardware encoding.

Will the behaviour change in near future so that we can add filters even for Hardware encoding?

**Comment by jpxiong** [comment]
Yes! We will add the feature into Hardware encoding in next version.

**Comment by jpxiong** [comment]
The newest demo includes what you want.
