### ISSUE TITLE
Unexpected delay in onRestartStreamingHandled()

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#70]
I am testing the new API feature of StreamingSessionListener (onRestartStreamingHandled).

Basically I disconnect the internet and reconnect immediately. And in the code I call startStreaming after about 10 secs.

In the logs you can see the 10sec difference here

11-29 17:38:41.878 D/pldroid_core_packet: free_packet_data 
11-29 17:38:52.147 D/pldroid_core_packet: initialize

But after the startStreaming() is called, it is taking around 30secs to again start the streaming.

11-29 17:38:52.997 E/pldroid_core_packet: rtmp_logcallback not ready.
11-29 17:39:23.007 E/pldroid_core_packet: rtmp_logcallback not ready. ===> 30s differerence
11-29 17:39:23.008 E/pldroid_core_packet: rtmp_logcallback not ready.
11-29 17:39:23.008 D/pldroid_core_packet: stream_state_callback state=3
11-29 17:39:23.008 D/pldroid_core_packet: stream_state_callback state=1

1) Is this expected behaviour to take 30s to actually start the streaming. Normally startStreaming does not take that long? 
2) I also see that right before streaming restarts (which is about 30s after startStreaming is called), Pili sdk is closing the connection with the remote rtmp server and restarting the connection. But the expected behaviour is that Pili sdk should simply start streaming new audio/video data without resetting the connection.

In our test server we have nginx rtmp servers with the setting of drop_idle_publishers 120s. So RTMP server wait for 120s if the publisher is not sending any data. But in this case, calling startStreaming() again in OnRestartStreamingHandled() is actually sending a terminating signal to end the session.  So basically there should be another function called CameraStreamingManager.restartStreaming() which should simply re-establish the broken connection and start streaming the data without resetting the connection.

This is important for lot of scenarios. In our case, once the session ends, we do lot of post processing. So if Pili terminates the connection on call to startStreaming, then we have incomplete data on the rtmp servers. 

My Code: 

 @Override
    public boolean onRestartStreamingHandled(int err) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                mLiveBanner.setText("RECONNECTING...");
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        mCameraStreamingManager.startStreaming();
                    }
                }, 10000);
            }
        });

        return true;
    }

[StreamingSessionListener_logs.txt](https://github.com/pili-engineering/PLDroidCameraStreaming/files/46602/StreamingSessionListener_logs.txt)

**Comment by jpxiong** [comment]
NO. Something you missed here.

`onRestartStreamingHandled ` is invoked **after the connection terminated**.  You do no need do like this:
```
new Handler().postDelayed(new Runnable() {
@Override
public void run() {
mCameraStreamingManager.startStreaming();
}
}, 10000);
```
just remove the 10s' delay and simply do `return mCameraStreamingManager.startStreaming();`

If you only `return false;` in `onRestartStreamingHandled`, `STATE.SHUTDOWN` message will be called.

**Comment by gouravd** [comment]
This is just a test and hence I wanted to retry .startStreaming() after 10s. The problem is 30s delay after the startStreaming is called.

11-29 17:38:52.997 E/pldroid_core_packet: rtmp_logcallback not ready.
11-29 17:39:23.007 E/pldroid_core_packet: rtmp_logcallback not ready. ===> 30s differerence


Regarding the connection termination. I understand the callback is called after connection in Pili is terminated. But the connection to the RTMp server is not terminated. The RTMP continues to listen for more data for atleast 120s after the disconnect. But when the startStreaming is called again the connection on the RTMP server is closed.

I am referring to this setting in NGinx rtmp

https://github.com/arut/nginx-rtmp-module/wiki/Directives#drop_idle_publisher

**Comment by jpxiong** [comment]
Please ignore the `rtmp_logcallback not ready.`. 

More details about `onRestartStreamingHandled`:
You will receive the `STATE.DISCONNECTED` message first, and then `onRestartStreamingHandled`  will be invoked.

PLDroidCameraStreaming wouldn't care about the RTMP server logical and only care the connection if broken.

**Comment by gouravd** [comment]
I might agree of the RTMP server part of the argument, but not about the delay. The problem is simple...the actual streaming is starting after 30secs of calling startStreaming. This is what I see in logs

11-29 17:38:52.147 D/pldroid_core_packet: initialize
....
....
11-29 17:39:23.008 D/pldroid_core_packet: stream_state_callback state=1

at time 17:38:52.147 (5:38:52 pm) the startStreaming is called, but the actual streaming is starting at 17:39:23 (5:29:23 pm). A 30 sec delay

**Comment by jpxiong** [comment]
Which handset?

**Comment by gouravd** [comment]
Motorola MotoG 2nd Gen and Micromax Yureka

**Comment by jpxiong** [comment]
Please verify on v1.4.5. Thanks.

**Comment by jpxiong** [comment]
Close since have no feedback.
