### ISSUE TITLE
Is the new Orientation change feature only available for Software encoding?

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidCameraStreaming#74]
1) Is the new Orientation change feature only available for Software encoding?
2) Does the streaming actually stop and restarts or is the behaviour same as that of camera switch(no stopping and restarting of streaming)

**Comment by jpxiong** [comment]
1) Only support on Software encoding right now
2) It only take effect after restarts streaming

**Comment by gouravd** [comment]
I am slightly confused about how to use this.

1) Do we have to stop and restart streaming in Activity's onConfigurationChange() call
2) Do we call CameraStreamingManager.stop() and then Start() after cameraStreamingManager.notifyActivityOrientationChanged();

**Comment by jpxiong** [comment]
1) Yes
2) Yes
