### ISSUE TITLE
YouTube RMTP

### ISSUE THREAD

**Issue by Alexanik** [pili-engineering/PLDroidCameraStreaming#79]
Good afternoon. Sorry for my English, I use a translator. I'm trying to send a stream of RTMP servers on Youtube, but I can not understand exactly what I have in JasonObject transfer library. I try to set res value = res = "{'id': 'live2', 'hub': '/', 'title': 'live2', 'publishKey': 'key', 'publishSecurity': 'securitys', 'hosts': {'publish': { 'rtmp': 'rtmp://a.rtmp.youtube.com/live2/amiroshnikov164.is_youtube_key_value' } } }"; but i have case CameraStreamingManager.STATE.IOERROR: on start. Could you help me? Thank you.

**Comment by jpxiong** [comment]
You should pass a valid `Stream` from Pili Streaming Cloud. 

About IOEEROR:
```
        /**
         * Connect error.
         *
         * The following is the possible case:
         *
         * <ol>
         *     <li>Stream is invalid</li>
         *     <li>Network is unreachable</li>
         * </ol>
         *
         * */
```
